<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>TokenFight.Game</PackageId>
        <Authors>Suntion</Authors>
        <Description>游戏角色, 数据, 副本与显示的实现</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <ItemGroup>
        <None Update="data\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Remove="core\actors\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Libraries\TokenFight.Core\TokenFight.Core.csproj" />
        <ProjectReference Include="..\Libraries\TokenFight.DI\TokenFight.DI.csproj" />
        <ProjectReference Include="..\Libraries\TokenFight.Reflection\TokenFight.Reflection.csproj" />
    </ItemGroup>

<!--    &lt;!&ndash;  编译为本机代码  &ndash;&gt;-->
<!--    <PropertyGroup>-->
<!--        <PublishAot>true</PublishAot>-->
<!--    </PropertyGroup>-->

</Project>
