<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>TokenFight.Core</PackageId>
        <Authors>Suntion</Authors>
        <Description>游戏核心战斗逻辑的实现</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="Models\Factories\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1"/>
        <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.11"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="Databases\Models\Inventory\**"/>
        <Compile Remove="Databases\Models\DataTable\**"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Remove="Databases\Models\Inventory\**"/>
        <EmbeddedResource Remove="Databases\Models\DataTable\**"/>
    </ItemGroup>
    <ItemGroup>
        <None Remove="Databases\Models\Inventory\**"/>
        <None Remove="Databases\Models\DataTable\**"/>
    </ItemGroup>

</Project>
