<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>TokenFight.UI</PackageId>
        <Authors>Suntion</Authors>
        <Description>游戏UI相关实现</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\TokenFight.Core\TokenFight.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Terminal.Gui" Version="2.0.0-alpha.3865" />
    </ItemGroup>
    <ItemGroup>
        <!-- 排除整个示例文件夹及其子文件夹 -->
        <Compile Remove="Examples\**\*.cs" />
    </ItemGroup>
</Project>
