<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>TokenFight.DI</PackageId>
        <Authors>Suntion</Authors>
        <Description>依赖注入相关模块</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TokenFight.Reflection\TokenFight.Reflection.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Json5Core" Version="1.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.AutoActivation" Version="10.0.0" />
    </ItemGroup>
</Project>
